apiVersion: v1
kind: Pod
metadata:
  name: k3s-pod
  namespace: k3s-namespace
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: k3s-container
      image: nginxinc/nginx-unprivileged:stable
      ports:
        - containerPort: 80
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
        requests:
          memory: "64Mi"
          cpu: "50m"
