apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: k3s-namespace
spec:
  containers:
  - image: nginx:latest
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
