apiVersion: v1
kind: Service
metadata:
  labels:
    app: video18
  name: video18-svc
  namespace: k3s-namespace
spec:
  clusterIP: 10.43.69.245
  clusterIPs:
  - 10.43.69.245
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: whatever
    port: 32769
    protocol: TCP
    targetPort: 80
  selector:
    app: video18
  sessionAffinity: None
  type: ClusterIP
